[build]
  command = "npm run build"
  publish = "out"

[[redirects]]
  from = "/eras/modern/"
  to = "/eras/19th-century/"
  status = 301

[[redirects]]
  from = "/eras/modern"
  to = "/eras/19th-century/"
  status = 301
